### ISSUE TITLE
DOC - Falha de Fato Incorreto - Persistência de Informação

### ISSUE THREAD

**Issue by elliasmatheus** [elliasmatheus/Source-Code-Inspection#1]
O Relatório de requisitos especifica que devem ser mantidas a soma total da quantidade de dinheiro que a máquina coletou durante toda a operação, no entanto deveria manter salvo às transações e o saldo final que é a soma do dinheiro devolvido subtraído da soma do dinheiro recebido com o dinheiro que já tinha anteriormente na máquina. Saber o número de transações (tickets vendidos, trocos entregues, saldos alimentados) são importantes para que se haja controle de lucro, prejuízo e de possíveis furtos por aproveitamento dessa falha.

**Comment by kaiquerodrigues88** [comment]
Essa Issue é uma falha de documentação, portanto, não poderá ser solucionada

**Comment by elliasmatheus** [comment]
Corrigido na revisão `"Correção proposta para a Issue #01"` da página Engenharia de Requisitos na wiki.
