### ISSUE TITLE
DOC - Falha de Omissão - Falta de Recursos

### ISSUE THREAD

**Issue by kaiquerodrigues88** [elliasmatheus/Source-Code-Inspection#2]
O relatório não especifica o que deve ser feito caso a máquina fique sem troco e/ou papel de bilhete

**Comment by elliasmatheus** [comment]
Essa issue é uma falha de documentação e que portanto não poderá ser ajustada.

**Comment by elliasmatheus** [comment]
Falha corrigida na revisão `"Correção proposta para as Issue #02 e #03"` da pagina Engenharia de Requisitos na wiki
